### ISSUE TITLE
I cannot run graph init successfully

### ISSUE THREAD

**Issue by Wysten-Hgg** [graphprotocol/graph-cli#995]
I learned to install graph from [here](https://thegraph.com/docs/en/cookbook/quick-start/). The following errors occurred when I ran ``graph init``.
```
✖ Failed to generate code from ABI and GraphQL schema: Command failed: yarn codegen

Error: Cannot find module '../node_modules/@float-capital/float-subgraph-uncrashable/src/Index.bs.js'

```

**Comment by mfolnovic** [comment]
I'd also like to add that in CI, I get an error (retracted for readability):

```
.../rescript@9.1.4/node_modules/rescript postinstall$ node scripts/install.js
.../rescript@9.1.4/node_modules/rescript postinstall: ninja not compatible? Error: Command failed: "/builds/croz/blockchain/enterprise-blockchain-poc/node_modules/.pnpm/rescript@9.1.4/node_modules/rescript/linux/ninja.exe" --version

...

.../rescript@9.1.4/node_modules/rescript postinstall: No prebuilt Ninja, building Ninja now
.../rescript@9.1.4/node_modules/rescript postinstall: env: can't execute 'python': No such file or directory
```

this is somewhat connected to this issue since the cause is adding `@float-capital/float-subgraph-uncrashable`, which pulls `rescript` (that can be clearly seen in changes of yarn.lock [here](https://github.com/graphprotocol/graph-cli/commit/0fe7662f6d21da0e4035977564d3330b47e0bbf2))

**Comment by evaporei** [comment]
Hey @Wysten-Hgg can you try version `0.36.1` please? We just released a fix :wink:

**Comment by schmidsi** [comment]
@evaporei thanks a lot. It fixed it for me.

**Comment by mfolnovic** [comment]
@schmidsi yes, it works with 0.35.0

I'm already on 0.35.0 (using Graph for a while now), my above error was detected during automatic update (renovate).

From what I've seen, I assume the fix in 0.36.1 won't fix my issue.

**Comment by schmidsi** [comment]
@mfolnovic can you try again and if it still preserves, open a new issue here?
